import { FbCliError } from "../errors/fbcli-error.js";

export type GraphNodeType = "user" | "ad_account" | "campaign" | "adset" | "ad" | "creative";

export type GraphEdgeDefinition = {
  name: string;
  description: string;
  read: boolean;
  write: boolean;
  mvpReadAllowed: boolean;
};

export type GraphNodeDefinition = {
  type: GraphNodeType;
  displayName: string;
  rootPathTemplate: string;
  idPrefixes: string[];
  edges: Record<string, GraphEdgeDefinition>;
};

const edge = (
  name: string,
  description: string,
  options: { read?: boolean; write?: boolean; mvpReadAllowed?: boolean } = {},
): GraphEdgeDefinition => ({
  name,
  description,
  read: options.read ?? true,
  write: options.write ?? false,
  mvpReadAllowed: options.mvpReadAllowed ?? true,
});

export const GRAPH_RESOURCES: Record<GraphNodeType, GraphNodeDefinition> = {
  user: {
    type: "user",
    displayName: "Ad Account User",
    rootPathTemplate: "/{AD_ACCOUNT_USER_ID}",
    idPrefixes: ["user_", "usr_"],
    edges: {
      adaccounts: edge("adaccounts", "All ad accounts associated with this person."),
      accounts: edge("accounts", "All pages and places managed by this person."),
      promotable_events: edge("promotable_events", "All promotable events."),
    },
  },
  ad_account: {
    type: "ad_account",
    displayName: "Ad Account",
    rootPathTemplate: "/act_{AD_ACCOUNT_ID}",
    idPrefixes: ["act_"],
    edges: {
      ads: edge("ads", "Ads data for this ad account."),
      adsets: edge("adsets", "Ad sets for this ad account."),
      campaigns: edge("campaigns", "Campaigns for this ad account."),
      insights: edge("insights", "Insights and reporting interface."),
      users: edge("users", "Users associated with this ad account."),
      adcreatives: edge("adcreatives", "Ad creatives library for this account."),
      adimages: edge("adimages", "Ad images library for this account."),
      advideos: edge("advideos", "Ad videos library for this account."),
      customaudiences: edge("customaudiences", "Custom audiences owned by this account.", {
        write: true,
        mvpReadAllowed: false,
      }),
    },
  },
  campaign: {
    type: "campaign",
    displayName: "Campaign",
    rootPathTemplate: "/{AD_CAMPAIGN_ID}",
    idPrefixes: ["campaign_", "cmp_"],
    edges: {
      ads: edge("ads", "Ads in this campaign."),
      adsets: edge("adsets", "Ad sets in this campaign."),
      insights: edge("insights", "Campaign insights."),
    },
  },
  adset: {
    type: "adset",
    displayName: "Ad Set",
    rootPathTemplate: "/{AD_SET_ID}",
    idPrefixes: ["adset_"],
    edges: {
      activities: edge("activities", "Action log for this ad set."),
      ads: edge("ads", "Ads in this ad set."),
      adcreatives: edge("adcreatives", "Ad creatives for this ad set."),
      insights: edge("insights", "Ad set insights."),
    },
  },
  ad: {
    type: "ad",
    displayName: "Ad",
    rootPathTemplate: "/{AD_ID}",
    idPrefixes: ["ad_"],
    edges: {
      adcreatives: edge("adcreatives", "Creative attached to this ad."),
      insights: edge("insights", "Ad insights."),
      leads: edge("leads", "Leads generated by this ad."),
      previews: edge("previews", "Generated previews for this ad."),
    },
  },
  creative: {
    type: "creative",
    displayName: "Ad Creative",
    rootPathTemplate: "/{AD_CREATIVE_ID}",
    idPrefixes: ["creative_", "crt_"],
    edges: {
      previews: edge("previews", "Generated previews for this creative."),
    },
  },
};

const NODE_TYPE_ALIASES: Record<string, GraphNodeType> = {
  user: "user",
  ad_account: "ad_account",
  account: "ad_account",
  campaign: "campaign",
  adset: "adset",
  ad_set: "adset",
  ad: "ad",
  creative: "creative",
  adcreative: "creative",
};

export function parseGraphNodeType(input: string): GraphNodeType {
  const normalizedInput = input.trim().toLowerCase();
  const nodeType = NODE_TYPE_ALIASES[normalizedInput];

  if (!nodeType) {
    throw new FbCliError("INVALID_NODE_TYPE", `Unsupported node type: ${input}`, {
      supportedNodeTypes: Object.keys(NODE_TYPE_ALIASES),
    });
  }

  return nodeType;
}

export function listGraphNodes(): GraphNodeDefinition[] {
  return Object.values(GRAPH_RESOURCES);
}

export function listGraphEdges(nodeType: GraphNodeType): GraphEdgeDefinition[] {
  return Object.values(GRAPH_RESOURCES[nodeType].edges);
}

export function inferGraphNodeTypeFromId(id: string): GraphNodeType {
  if (id.startsWith("act_")) {
    return "ad_account";
  }

  for (const [nodeType, definition] of Object.entries(GRAPH_RESOURCES)) {
    for (const prefix of definition.idPrefixes) {
      if (id.startsWith(prefix)) {
        return nodeType as GraphNodeType;
      }
    }
  }

  if (/^\d+$/.test(id)) {
    throw new FbCliError(
      "AMBIGUOUS_GRAPH_ID",
      "Numeric Graph IDs are ambiguous. Pass --node-type for this command.",
      { id },
    );
  }

  throw new FbCliError("INVALID_GRAPH_ID", `Cannot infer node type from ID: ${id}`, { id });
}

export function normalizeGraphId(id: string): string {
  const normalizedId = id.trim().replace(/^\//, "");

  if (!normalizedId || normalizedId.includes("/")) {
    throw new FbCliError("INVALID_GRAPH_ID", `Invalid Graph ID: ${id}`, {
      id,
    });
  }

  return normalizedId;
}
